### ISSUE TITLE
A typo, but crash all the functionality.

### ISSUE THREAD

**Issue by lzane** [rikoroku/toggl_integrator#1]
Just wanna point out there are a typo in `lib/toggl_integrator/google_calendar.rb` line 33.

![image](https://user-images.githubusercontent.com/12814398/35848336-bedd2000-0b58-11e8-802e-2a71993c1460.png)

missing a ','

really appreciate your project, thx~

**Comment by rikoroku** [comment]
Thank you for pointing out:)
Close it, because merged your pull request. thx!!
